name: Generate orthography.md
run-name: Generate orthography.md
on: 
  push:
    branches:
      - main
    paths:
      - orthography.csv

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Do a sparse checkout on given patterns. Each pattern should be separated with
          # new lines.
          # Default: null
          sparse-checkout: |
            docs/
            scripts/
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - run: |
          python scripts/csv-to-md.py or
          sed -i "0,/last_modified_at.*/s//last_modified_at: $(date -Iseconds)/" docs/orthography.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
    # Optional. Commit message for the created commit.
    # Defaults to "Apply automatic changes"
          commit_user_name: git-auto-commit-action
          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: docs/orthography.md
