name: Run csv-to-st.py
run-name: csv-to-st
on: 
  push:
    branches:
      - main
    paths:
      - style.csv

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run-CSV-To-St_PY:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Do a sparse checkout on given patterns. Each pattern should be separated with
          # new lines.
          # Default: null
          sparse-checkout: |
            obsolete.csv
            csv-to-md.py
            docs/style.md
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - run: |
          python csv-to-st.py st
          sed -i "0,/last_modified_at.*/s//last_modified_at: $(date -Iseconds)/" docs/style.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
    # Optional. Commit message for the created commit.
    # Defaults to "Apply automatic changes"
          commit_user_name: git-auto-commit-action
          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: docs/style.md
